config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

XeroEngine::Engine.routes.draw do

  devise_for :users,
             class_name: "XeroEngine::User", module: :devise,
             path: 'user',
             sign_out_via: [ :get, :post, :delete ],
             controllers: { registrations: "xero_engine/registrations" }

  resources :organisation_memberships, path: :connections do
    member do
      get :expired
    end
  end
  get '/oauth/callback', to: 'organisation_memberships#create'

  resources :billing_transactions, path: 'billing'
  resources :payment_methods, only: [ :create, :destroy ]

  resources :organisations do
    resource :print_settings, path: :settings
  end

  get '/dashboard', to: 'dashboard#index', as: :dashboard

  authenticate :user, lambda { |u| u.email == ENV.fetch('ADMIN_EMAIL') } do
    mount Sidekiq::Web => '/sidekiq-monitoring'
  end
end

app/models/xero_engine/organisation.rb
module XeroEngine
  class Organisation < ActiveRecord::Base
    include Stripe::Callbacks

    # AR callbacks
    after_create :after_create_callback

    # Relationships
    has_many :organisation_memberships
    has_many :users, through: :organisation_memberships
    has_many :billing_transactions, dependent: :destroy

    # Validations
    validates :name, presence: true
    validates :short_code, presence: true

    attr_accessor :stripe_token, :coupon, :xero_client

    # Is org actively being used within our app? We can use this information
    # to not include it in backend processes, for instance, since noone's paying
    # for it.
    def active?
      user_ids.any?
    end

    def has_credit?(cost=0)
      self.credit_amount(false) >= cost
    end

    def credit_amount(completed_only=true)
      cond = completed_only ? { completed: true } : {}
      value = self.billing_transactions.credit.where(cond).sum(:amount_cents) - self.billing_transactions.debit.where(cond).sum(:amount_cents)
      Money.new value, 'USD'
    end

    def debit_amount(options={ this_month: true })
      0
    end

    def created_by
      self.users.first
    end

    def has_auto_top_up?
      auto_top_up_amount != nil && auto_top_up_amount > 0
    end

    def stripe_card
      stripe_customer.cards.first if stripe_customer
    end

    def stripe_customer
      @stripe_customer ||=
        begin
          if stripe_customer_id.blank?
            nil
          else
            Stripe::Customer.retrieve(stripe_customer_id)
          end
        rescue Stripe::InvalidRequestError => e
          # Invalid parameters were supplied to Stripe's API
          puts e.inspect
          if e.http_status == 404
            # This customer doesn't exist. We might as well clear it out.
            puts "Clearing 404'd customer record"
            update(stripe_customer_id: nil)
          end
          nil
        rescue => e
          puts e.inspect
          nil
        end
    end

    def create_stripe_customer(created_by, card_stripe_token=nil)
      return stripe_customer if stripe_customer_id

      customer_params = {
        description: "#{name}",
        email: created_by.email,
        card: card_stripe_token,
        metadata: {
          'organisation_id' => id,
          'organisation_name' => name,
          'created_by_user_id' => created_by.id,
          'created_by_user_name' => created_by.name,
          'created_by_user_email' => created_by.email
        }
      }

      customer = Stripe::Customer.create customer_params
      update!(stripe_customer_id: customer.id)

      customer
    end

    def create_stripe_card(stripe_token)
      if stripe_card
        raise "This organisation already has a card ending #{stripe_card['last4']} stored for it. Delete this card before creating a new one."
      else
        stripe_customer.cards.create(:card => stripe_token)
      end
    end

  private

    # AR callbacks

    def after_create_callback
      # self.create_print_settings
      OrganisationPostCreationWorker.perform_async(self.short_code)
    end

    # Stripe webhook callbacks

    # after_customer_created! do |customer, event|
    #   # Nothing
    # end

    after_customer_deleted! do |customer, event|
      Organisation.find(stripe_customer_id: customer.id).update(stripe_customer_id: nil)
    end

    # after_customer_card_deleted! do |customer, event|
    #   #
    # end
    #
    # after_customer_card_updated! do |customer, event|
    #   # Nothing
    # end

    after_stripe_event do |target, event|
      Rails.logger.info "Stripe event: \n" + target.inspect + "\n" + event.inspect
    end

  end
end

app/controllers/concerns/xero_engine/current_organisation.rb
module XeroEngine::CurrentOrganisation

  extend ActiveSupport::Concern

  included do
    before_filter :ensure_current_organisation, :redirect_root_to_dashboard
    helper_method :current_organisation, :current_organisation?, :current_organisation_membership
  end

  # @return {Organisation} current organisation being used to access the Xero API
  def current_organisation
    current_organisation_membership.organisation if has_current_organisation?
  end

  # @return {OrganisationMembership}
  def current_organisation_membership
    @current_organisation_membership ||= if current_user && has_current_organisation?
                                           org = current_user.organisation_memberships.find_by_short_code current_organisation_short_code
                                           set_current_organisation_short_code nil if org.nil?
                                           org
                                         else
                                           nil
                                         end
  end

  # Session state for the current organisation ID
  def current_organisation_short_code
    session[:current_organisation_short_code]
  end

  # Set the sessions state for the current organisation
  def set_current_organisation_short_code(short_code_or_org)
    if short_code_or_org.respond_to? :short_code
      session[:current_organisation_short_code] = short_code_or_org.short_code
    else
      session[:current_organisation_short_code] = short_code_or_org
    end
  end

  # @return {boolean} Has the user picked an Organisation
  def current_organisation?
    user_signed_in? && current_organisation_short_code.present? && current_organisation.present?
  end

  # ---- Filters ----

  def ensure_current_organisation
    if user_signed_in? && (controller_name != 'pages' || request.path == xero_engine.root_path) &&
       (controller_name != 'organisation_memberships')
      if current_organisation_short_code.blank? #&& current_organisation
        if current_user.organisation_memberships.count == 1
          set_current_organisation_short_code current_user.organisation_memberships.first.short_code
        else
          message = (current_user.organisation_memberships.count == 0) ? nil :
                      I18n.t('xero_engine.organisation_memberships.select_organisation')
          redirect_to organisation_memberships_path, notice: message
        end
      end
    end
  end

  def redirect_root_to_dashboard
    if request.path == '/' && user_signed_in?
      redirect_to dashboard_path if current_organisation?
    end
  end

  private

  def has_current_organisation?
    current_organisation_short_code.present? && current_user && current_user.organisation_memberships.find_by_short_code(current_organisation_short_code).present?
  end

end

app/controllers/concerns/xero_engine/xero_client.rb
module XeroEngine::XeroClient
  extend ActiveSupport::Concern

  # @return {Xeroizer::PublicApplication} configured client with access to the #current_organisation
  def xero_client
    @xero_client ||= Xeroizer::PublicApplication.new Rails.application.secrets.xero_consumer_key, Rails.application.secrets.xero_consumer_secret, :logger => Rails.logger
    if current_organisation?
      membership = current_user.organisation_memberships.where(short_code: current_organisation_short_code).first
      @xero_client.authorize_from_access membership.access_token, membership.access_secret if membership.present?
    end
    @xero_client
  end

end

app/controllers/concerns/xero_engine/xero_oauth.rb
module XeroEngine::XeroOauth
  extend ActiveSupport::Concern

  included do
    rescue_from Xeroizer::OAuth::TokenExpired, with: :access_token_expired
    rescue_from Xeroizer::OAuth::TokenInvalid, with: :access_token_invalid
  end

  # Rescue from OAuth errors
  def access_token_expired
    begin
      xero_client.renew_access_token(current_organisation_membership.access_token, 
                                    current_organisation_membership.access_secret, 
                                    current_organisation_membership.session_handle)
    rescue
      if current_organisation?
        current_organisation_membership.update_attributes access_token: nil, access_secret: nil, session_handle: nil
      end

      redirect_to expired_organisation_membership_path(current_organisation_membership)
    end
  end

  def access_token_invalid
    if current_organisation?
      current_organisation_membership.update_attributes access_token: nil, access_secret: nil, session_handle: nil
    end
    if current_organisation_membership
      redirect_to expired_organisation_membership_path(current_organisation_membership), alert: 'There was a problem connecting to Xero'
      return
    else
      redirect_to organisation_memberships_path
    end
  end

end

app/controllers/xero_engine/application_controller.rb
module XeroEngine
  class ApplicationController < ActionController::Base

    # Concerns
    include CurrentOrganisation

    # Helpers
    helper ApplicationHelper

    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    # Prevent a page from being cached by calling this
    def disable_caching
      expires_now
    end

    private

    def after_sign_up_path_for(resource)
      xero_engine.new_organisation_membership_path
    end

    def after_sign_in_path_for(resource)
      session["user_return_to"] || xero_engine.root_path
    end

    def after_sign_out_path_for(resource)
      xero_engine.root_path
    end

  end
end

app/controllers/xero_engine/authorised_controller.rb
module XeroEngine
  class AuthorisedController < ApplicationController

    # Concerns
    include Pundit
    include XeroClient
    include XeroOauth

    # Filters
    before_filter :authenticate_user!,
                  :ensure_current_organisation,
                  :warn_no_stripe_card_payment_method

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    # Call from a controller to hide the page navigation structure
    def hide_secondary_navbar
      @hide_secondary_navbar = true
    end

    # Rescue from Pundit auth errors
    def user_not_authorized
      redirect_to request.referrer || root_url, alert: 'Access denied'
    end

    def warn_no_stripe_card_payment_method
      if current_organisation? && current_organisation.stripe_card.nil?
        flash[:warning] = I18n.t 'xero_engine.payment_method.missing'
      end
    end

  end
end

app/controllers/xero_engine/billing_transactions_controller.rb
module XeroEngine
  class BillingTransactionsController < AuthorisedController

    # skip_before_filter :warn_no_stripe_card_payment_method
    # before_filter :disable_caching

    def index
      flash.delete(:warning) if flash[:warning]
      @credit_transactions = current_organisation.billing_transactions.credits.limit(10)
      @credit_transaction = current_organisation.billing_transactions.new transaction_type: :credit, created_by: current_user, amount_cents: 0
    end

    # def new
    #   @credit_transaction = current_organisation.billing_transactions.new transaction_type: :credit, created_by: current_user, amount_cents: 0
    # end

    def create
      @credit_transaction = current_organisation.billing_transactions.new(
          transaction_type: :credit,
          created_by: current_user,
          amount_cents: billing_transaction_params[:amount_cents].to_i
      )

      if @credit_transaction.save
        if billing_transaction_params[:auto_top_up]
          current_organisation.update(auto_top_up_amount: billing_transaction_params[:amount_cents])
        end

        flash[:success] = I18n.t 'billing_transaction.creation.success', amount: @credit_transaction.amount, :scope => [:xero_engine]
        redirect_to @credit_transaction
      else
        message = I18n.t 'billing_transaction.creation.error', :scope => [:xero_engine]
        redirect_to :back, alert: message
      end
    end

    def show
      @credit_transaction = current_organisation.billing_transactions.credits.find(params[:id])
    end

    def billing_transaction_params
      params.require(:billing_transaction).permit(:amount_cents, :auto_top_up)
    end

  end
end

app/controllers/xero_engine/dashboard_controller.rb
module XeroEngine
  class DashboardController < AuthorisedController

  end
end

app/controllers/xero_engine/organisation_memberships_controller.rb
module XeroEngine
  class OrganisationMembershipsController < XeroEngine::AuthorisedController

    skip_before_filter :ensure_current_organisation

    def index
      @organisation_memberships = current_user.organisation_memberships
    end

    def new
      oauth_callback_url = "#{ENV.fetch('SITE_URL')}/oauth/callback"

      Rails.logger.info "Requesting OAuth access with callback #{oauth_callback_url}"

      request_token = xero_client.request_token(:oauth_callback => oauth_callback_url)
      session[:request_token] = request_token.token
      session[:request_secret] = request_token.secret

      redirect_to request_token.authorize_url
    end

    def create
      xero_client.authorize_from_request session[:request_token], session[:request_secret], oauth_verifier: params[:oauth_verifier]

      # Clean up the session
      session[:request_token] = nil
      session[:request_secret] = nil

      # Track the currently logged in organisation
      @organisation = XeroOrganisationSyncService.new(current_user, xero_client).create_or_update!
      set_current_organisation_short_code @organisation.short_code

      render :callback, layout: false

    rescue OAuth::Unauthorized
      redirect_to organisation_memberships_path, alert: "Failed to connect to Xero. Try again."
    end

    def show
      # Switch organisations
      @membership = current_user.organisation_memberships.find(params[:id])
      authorize @membership
      set_current_organisation_short_code @membership.short_code
      flash.clear # Start with a new slate for this org
      redirect_to root_path
    end

    def expired
      hide_secondary_navbar

      @membership = current_user.organisation_memberships.find(params[:id])
      authorize @membership

      @organisation = @membership.organisation
      set_current_organisation_short_code @membership.short_code
    end

    def destroy
      @membership = current_user.organisation_memberships.find(params[:id])
      authorize @membership

      flash[:success] = I18n.t 'organisation_membership.destruction.success', organisation_name: @membership.organisation.name, :scope => [:xero_engine]
      @membership.destroy!

      set_current_organisation_short_code nil

      redirect_to root_path
    end

  protected

    def xero_client
      @xero_client ||= Xeroizer::PublicApplication.new Rails.application.secrets.xero_consumer_key, Rails.application.secrets.xero_consumer_secret
    end

  end
end

app/controllers/xero_engine/payment_methods_controller.rb
module XeroEngine
  class PaymentMethodsController < ApplicationController

    skip_before_filter :warn_no_stripe_card_payment_method
    before_filter :disable_caching

    def create
      if current_organisation.stripe_customer.nil?
        # There is no customer yet, so create one, passing in the card that way
        current_organisation.create_stripe_customer(current_user, params[:stripeToken])
      else
        # The customer already exists, so just create it using the .card access path
        current_organisation.create_stripe_card(params[:stripeToken])
      end

      flash[:success] = I18n.t 'payment_method.creation.success', :scope => [:xero_engine]
      redirect_to :back
    end

    def destroy
      current_organisation.stripe_card.delete if current_organisation.stripe_card
      flash[:success] = I18n.t 'payment_method.destruction.success', :scope => [:xero_engine]
      redirect_to :back
    end

  end
end

app/controllers/xero_engine/registrations_controller.rb
module XeroEngine
  class RegistrationsController < Devise::RegistrationsController

    before_filter :update_sanitized_params, if: :devise_controller?

    def update_sanitized_params
      devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
      devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
    end

  end
end

app/helpers/xero_engine/application_helper.rb
module XeroEngine
  module ApplicationHelper

    @@head_stylesheets = []

    # def main_app
    #   Rails.application.class.routes.url_helpers
    # end

    def site_name
      ENV.fetch('SITE_NAME')
    end

    def site_url
      ENV.fetch('SITE_URL')
    end

    def head_stylesheet_tag(url)
      @@head_stylesheets << url
    end

    def head_stylesheet_tags
      @@head_stylesheets.map do |url|
        stylesheet_link_tag url
      end.join("\n").html_safe
    end

  end
end

app/views/xero_engine/billing_transactions/_add_credit_card_button.html.erb
<%= form_tag payment_methods_path, method: :post do |f| %>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= ENV.fetch('STRIPE_PUBLIC_KEY') %>"
          data-label="Add a card for this account"
          data-name="<%= site_name %>"
          data-email="<%= current_user.email %>"
          data-description="Add a card to your account"
          data-panel-label="Save Card"
          _data-amount="0"></script>
<% end %>

app/views/xero_engine/billing_transactions/_credit_card_form.html.erb
<div class="container">
  <div class="col-xs-4">
    <fieldset>
      <legend>Payment</legend>
      <div class="control-group">
        <label label-default="" class="control-label">Card Holder's Name</label>
        <div class="controls">
          <input type="text" class="form-control" pattern="\w+ \w+.*" title="First and last name" required="">
        </div>
      </div>
      <div class="control-group">
        <label label-default="" class="control-label">Card Number</label>
        <div class="controls">
          <div class="row">
            <div class="col-xs-3">
              <input type="text" class="form-control" autocomplete="off" maxlength="4" pattern="\d{4}" title="First four digits" required="">
            </div>
            <div class="col-xs-3">
              <input type="text" class="form-control" autocomplete="off" maxlength="4" pattern="\d{4}" title="Second four digits" required="">
            </div>
            <div class="col-xs-3">
              <input type="text" class="form-control" autocomplete="off" maxlength="4" pattern="\d{4}" title="Third four digits" required="">
            </div>
            <div class="col-xs-3">
              <input type="text" class="form-control" autocomplete="off" maxlength="4" pattern="\d{4}" title="Fourth four digits" required="">
            </div>
          </div>
        </div>
      </div>
      <div class="control-group">
        <label label-default="" class="control-label">Card Expiry Date</label>
        <div class="controls">
          <div class="row">
            <div class="col-md-9">
              <select class="form-control" name="cc_exp_mo">
                <option value="01">January</option>
                <option value="02">February</option>
                <option value="03">March</option>
                <option value="04">April</option>
                <option value="05">May</option>
                <option value="06">June</option>
                <option value="07">July</option>
                <option value="08">August</option>
                <option value="09">September</option>
                <option value="10">October</option>
                <option value="11">November</option>
                <option value="12">December</option>
              </select>
            </div>
            <div class="col-md-3">
              <select class="form-control" name="cc_exp_yr">
                <option>2014</option>
                <option>2015</option>
                <option>2016</option>
                <option>2017</option>
                <option>2018</option>
                <option>2019</option>
                <option>2020</option>
                <option>2021</option>
                <option>2022</option>
              </select>
            </div>
          </div>
        </div>
      </div>
      <div class="control-group">
        <label label-default="" class="control-label">Card CVV</label>
        <div class="controls">
          <div class="row">
            <div class="col-md-3">
              <input type="text" class="form-control" autocomplete="off" maxlength="3" pattern="\d{3}" title="Three digits at back of your card" required="">
            </div>
            <div class="col-md-8"></div>
          </div>
        </div>
      </div>
      <div class="control-group">
        <label label-default="" class="control-label"></label>
        <div class="controls">
          <button type="submit" class="btn btn-primary">Submit</button>
          <button type="button" class="btn btn-default">Cancel</button>
        </div>
      </div>
    </fieldset>
  </div>
</div>
<hr>

app/views/xero_engine/billing_transactions/_credit_history.html.erb
<div class="panel-group" id="credit-history">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="btn-block" data-toggle="collapse" data-parent="#accordion" href="#creditHistoryCollapsible">
          <i class="fa fa-angle-down pull-right"></i> Payment history
        </a>
      </h4>
    </div>
    <div id="creditHistoryCollapsible" class="panel-collapse collapse">
    <%- if credit_history.size == 0 %>
      <div class="panel-body">
        <span class="text-muted">No top-up payments have been made.</span>
      </div>
    <%- else %>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Amount</th>
            <th>Date</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
        <% credit_history.each do |credit_transaction| %>
          <tr>
            <td><%= humanized_money_with_symbol credit_transaction.amount %></td>
            <td><%= credit_transaction.created_at.strftime("%l:%M%P, %b %d %Y") %></td>
            <td>
              <%- if credit_transaction.completed? %>
                <span class="label label-success">Paid</span>
              <%- else %>
                <span class="label label-warning" data-toggle="tooltip" data-placement="left" title="Payment is processing and hasn't yet been applied to your account balance.">Pending</span>
              <%- end %>
            </td>
          </tr>
        <%- end %>
        </tbody>
      </table>
    <%- end %>
    </div>
  </div>
</div>
<% content_for :javascript do %>
<script>
$(document).ready(function() {
  $('#credit-history .label-warning').tooltip();
});
</script>
<% end %>

app/views/xero_engine/billing_transactions/_manage_payment_method.html.erb
<div class="panel-group" id="card-details">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="btn-block" data-toggle="collapse" data-parent="#accordion" href="#cardDetailsCollapsible">
          <i class="fa fa-angle-down pull-right"></i> Manage payment method
        </a>
      </h4>
    </div>
    <div id="cardDetailsCollapsible" class="panel-collapse collapse">
      <div class="panel-body">
        <%- if defined?(manage_payment_method) %>
          <p>
            Payments are made using your stored <strong><%= manage_payment_method['brand'] %> card ending in <%= manage_payment_method['last4'] %></strong>, 
            expiring <%= "#{manage_payment_method['exp_month']}/#{manage_payment_method['exp_year']}" %> 
          </p>
          <p>
            <%= link_to "Remove this card", payment_method_path(id: manage_payment_method['id']), class: 'btn btn-danger', :data => { :confirm => "Are you sure?" }, :method => :delete %>
          </p>
        <%- else %>
          <span class="text-muted">No cards stored for this account</span>
        <%- end %>
      </div>
    </div>
  </div>
</div>

app/views/xero_engine/billing_transactions/_user_access.html.erb
<div class="panel-group" id="userAccess">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="btn-block" data-toggle="collapse" href="#userAccessCollapsible">
          <i class="fa fa-angle-down pull-right"></i> Users
        </a>
      </h4>
    </div>
    <div id="userAccessCollapsible" class="panel-collapse collapse">
      <div class="panel-body">
        <p class="text-muted small">
          The following users have access to this Xero organisation within <%= site_name %>, <%= user_access.name %>.
        </p>
        <ul class="list-unstyled">
          <%- user_access.users.each do |u| %>
          <li class="accesslevel-<%= u.role %>">
            <%= "#{u.name} (#{u.email})" %>
          </li>
          <%- end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/xero_engine/billing_transactions/index.html.erb
<div class="row">
  <div class="col-md-8">

    <div class="panel panel-default">
      <div class="panel-body">
        <div class="col-md-4 alert text-muted pull-left">
          <h1 class="h4">About Billing</h1>
          <p>Billing works on a pre-paid basis. Purchase top-up credit to fund your account.</p>
          <p>We'll warn you when you run low, or you can opt-in to automatically credit your account when it drops below $10.</p>
        </div>

        <div class="col-md-8">
          <h1>
            <span class="label label-info"><%= humanized_money_with_symbol current_organisation.credit_amount %></span>
            account credit
          </h1>

          <hr />

      <% if current_organisation.stripe_card %>
        <%= simple_form_for @credit_transaction do |f| %>
          <%= f.error_notification %>
          <%= render partial: 'xero_engine/shared/error_messages', object: @credit_transaction %>
          <h2 class="h4">Top up your account&hellip;</h2>

          <div class="form-group row">
            <div class="col-xs-6">
              <%= f.select :amount_cents, 
                          [['$10.00', 1000], 
                          ['$20.00', 2000], 
                          ['$50.00', 5000], 
                          ['$100.00', 10000], 
                          ['$200.00', 20000], 
                          ['$500.00', 50000],
                          ['$1000.00', 100000]], 
                          {}, 
                          { class: 'form-control input-lg' } %>
            </div>
          </div>

          <div class="form-group">
            <label><%= f.check_box :auto_top_up %> Auto top-up this amount when balance drops below $10</label>
          </div>

          <div>
            <p>
              <button type="submit" class="btn btn-primary btn-embossed btn-lg">
                <i class='fa fa-plus-circle'></i> Purchase Top-Up
              </button>
            </p>
            <p class="text-primary small">
              Paying with
              <strong>
                <%= current_organisation.stripe_card['brand'] %> card ending in <%= current_organisation.stripe_card['last4'] %>
              </strong>, 
              expiring <%= "#{current_organisation.stripe_card['exp_month']}/#{current_organisation.stripe_card['exp_year']}" %>
            </p>
          </div>
        <% end # form %>
      <% else %>

          <div>
            <p class="alert alert-warning" role="alert">
              You do not currently have any payment methods associated with your account.
              <strong>Please add a credit or debit card.</strong>
            </p>
            <p>
              <%= render partial: 'add_credit_card_button' %>
            </p>
          </div>

      <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <%= render partial: 'manage_payment_method', object: current_organisation.stripe_card %>
    <%= render partial: 'credit_history', object: @credit_transactions %>
    <%#= render partial: 'user_access', object: current_organisation %>
  </div>
</div>

app/views/xero_engine/billing_transactions/show.html.erb
<h1>
  Credit Payment
</h1>

<div>
  <% if @credit_transaction.completed? %>
  <small class="label label-success">Paid</small>
  <% else %>
  <p>
  <small class="label label-warning">Payment Processing</small>
  <strong>This payment has not yet cleared.</strong> It may take a few minutes to process before becoming available on your account.</p>
  <% end %>
</div>

<hr/>
<p>
  Topped up <%= humanized_money_with_symbol @credit_transaction.amount %> 
  on <%= @credit_transaction.created_at.to_formatted_s(:long_ordinal) %>
</p>

<p>
  <%= link_to 'Back to Payments', billing_transactions_path, class: 'btn btn-default' %>
</p>
<%#= @credit_transaction.inspect %>